<?php

namespace Trunk\Console\Command;

use React\EventLoop\Loop;
use ReflectionClass;
use Trunk\Database\Connection;
use Trunk\Database\ORM\Attributes\Entity;
use Trunk\Database\Schema\Diff\SchemaComparator;
use Trunk\Database\Schema\Diff\SchemaIntrospector;
use Trunk\Database\Schema\Diff\SchemaReader;

class SchemaDiffCommand extends Command
{
    public static function description(): string
    {
        return 'Diff entities against the live database schema and generate a migration file';
    }

    public function handle(array $args): void
    {
        $this->app->bootProviders();

        $basePath = $this->app->getBasePath();
        $srcDir = "{$basePath}/src";

        if (!is_dir($srcDir)) {
            echo "No src directory found.\n";
            return;
        }

        $entities = $this->findEntities($srcDir);
        if (empty($entities)) {
            echo "No classes with #[Entity] attribute found.\n";
            return;
        }

        $db = $this->app->getContainer()->get(Connection::class);
        $expected = (new SchemaReader())->read($entities);

        (new SchemaIntrospector($db))->introspect()->then(
            function (array $actual) use ($db, $expected, $basePath) {
                $diff = (new SchemaComparator($db->grammar()))->diff($expected, $actual);

                if (empty($diff['up'])) {
                    echo "No schema changes required.\n";
                } else {
                    $this->generateMigrationFile($basePath, $diff['up'], $diff['down']);
                }

                Loop::get()->stop();
            },
            function (\Throwable $e) {
                echo 'Schema diff failed: ' . $e->getMessage() . "\n";
                Loop::get()->stop();
            }
        );

        Loop::get()->run();
    }

    private function findEntities(string $dir): array
    {
        $entities = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir));
        foreach ($iterator as $file) {
            if ($file->getExtension() === 'php') {
                $content = file_get_contents($file->getPathname());
                // Quick pre-filter to avoid parsing every file; matches both #[Entity] and
                // #[Entity(table: '...')] since the attribute may or may not take arguments.
                if (str_contains($content, '#[Entity')) {
                    if (
                        preg_match('/namespace\s+([^;]+);/i', $content, $nsMatch) &&
                        preg_match('/class\s+([a-zA-Z0-9_]+)/i', $content, $classMatch)
                    ) {
                        $className = trim($nsMatch[1]) . '\\' . trim($classMatch[1]);
                        if (!class_exists($className)) {
                            require_once $file->getPathname();
                        }
                        if (class_exists($className) && !empty((new ReflectionClass($className))->getAttributes(Entity::class))) {
                            $entities[] = $className;
                        }
                    }
                }
            }
        }

        return $entities;
    }

    private function generateMigrationFile(string $basePath, array $upStatements, array $downStatements): void
    {
        $migrationsDir = $basePath . '/database/migrations';
        if (!is_dir($migrationsDir)) {
            mkdir($migrationsDir, 0777, true);
        }

        $timestamp = date('Y_m_d_His');
        $filename = "{$timestamp}_schema_diff.php";
        $filepath = "{$migrationsDir}/{$filename}";

        $upBody = $this->compileChain($upStatements);
        $downBody = $this->compileChain($downStatements);

        $content = <<<PHP
<?php

use React\Promise\PromiseInterface;
use Trunk\Database\Migration;
use Trunk\Database\Schema\SchemaBuilder;

// Generated by `php trunk orm:schema-diff`: introspects the live database and adds
// whatever's missing (tables, columns, foreign keys). Never drops anything - edit
// this file by hand if you need to remove a column or table.
return new class extends Migration {
    public function up(SchemaBuilder \$schema): PromiseInterface
    {
        return {$upBody};
    }

    public function down(SchemaBuilder \$schema): PromiseInterface
    {
        return {$downBody};
    }
};
PHP;

        file_put_contents($filepath, $content);

        echo "Migration file generated: database/migrations/{$filename}\n";
        foreach ($upStatements as $sql) {
            echo '  + ' . strtok($sql, "\n") . "\n";
        }
    }

    private function compileChain(array $statements): string
    {
        if (empty($statements)) {
            return '\React\Promise\resolve(null)';
        }

        $calls = array_map(
            fn(string $sql) => '$schema->raw(' . var_export($sql, true) . ')',
            $statements
        );

        return implode("\n            ->then(fn() => ", $calls) . str_repeat(')', count($calls) - 1);
    }
}
